name: knowyourself
description: KYB - Physical & Mental Health Tracker is a comprehensive app that helps you track your overall well-being. With KYB, you can write journals, create to-do lists, and celebrate your accomplishments, all in one place.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

#  flutter_screenutil: ^5.9.0
#  local_auth: ^2.1.3
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  file_picker: ^8.0.0+1
  local_auth: ^2.2.0

  permission_handler: ^10.2.0
  awesome_notifications: ^0.9.3+1
  workmanager:
  cached_network_image:

  flutter_svg: ^2.0.10+1
  google_fonts: ^5.0.1
  intl: ^0.19.0

  smooth_page_indicator: ^1.0.1
  table_calendar: ^3.1.1
  timezone: ^0.9.1
  url_launcher: ^6.1.9

  http: ^0.13.5
  html: ^0.15.4
  youtube_player_flutter: ^9.0.0
#  youtube_player_iframe: ^5.1.1

  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  animated_emoji: ^3.1.0

  get: ^4.6.6
  get_storage: ^2.1.1
  lottie:
  google_sign_in: ^6.2.1

  image_picker: ^1.0.7
  geolocator: ^11.0.0
  geocoding:
  flutter_sound: ^9.2.13
  tflite_flutter: ^0.10.4
  firebase_ml_model_downloader: ^0.2.4+16


dependency_overrides:
  google_fonts: ^6.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/emojis/
    - assets/illustrations/
    - assets/avatars/
    - assets/brand/
    - assets/icons/
    - assets/animations/
    - assets/materials/
    - assets/mood-shifter/